// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datalayers")
	ScopeName = "github.com/emqx-ecp-devops/datalayersexporter"
)

const (
	TracesStability = component.StabilityLevelAlpha
	MetricsStability = component.StabilityLevelBeta
)
